/* ==========================================================================
   FlutterHub AI Developer Tools Suite
   - JSON to Dart Class Generator
   - Flutter Error Stack Trace Analyzer
   - Material 3 Color Theme Generator
   ========================================================================== */

const AITools = {


  jsonToDart: function (jsonStr, className = 'AutogeneratedModel') {
    try {

      if (!jsonStr.trim()) return '// Paste JSON object above to generate Dart code...';

      const obj = JSON.parse(jsonStr);

      let dartCode = `class ${className} {\n`;

      const keys = Object.keys(obj);


      keys.forEach(key => {
        const type = this.getDartType(obj[key]);
        dartCode += `  final ${type}? ${key};\n`;
      });

      dartCode += `\n  const ${className}({\n`;
      keys.forEach(key => {
        dartCode += `    this.${key},\n`;
      });

      dartCode += `  });\n\n`;

      dartCode += `  factory ${className}.fromJson(Map<String, dynamic> json) {\n`;
      dartCode += `    return ${className}(\n`;
      keys.forEach(key => {
        dartCode += `      ${key}: json['${key}'],\n`;
      });
      dartCode += `    );\n  }\n\n`;

      // toJson

      dartCode += `  Map<String, dynamic> toJson() {\n`;

      dartCode += `    return {\n`;

      keys.forEach(key => {

        dartCode += `      '${key}': ${key},\n`;

      });

      dartCode += `    };\n  }\n}`;


      return dartCode;

    } catch (e) {

      return `// JSON Syntax Error: ${e.message}`;

    }
  },

  getDartType: function (val) {
    if (val === null) return 'dynamic';
    if (typeof val === 'string') return 'String';
    if (typeof val === 'number') return Number.isInteger(val) ? 'int' : 'double';
    if (typeof val === 'boolean') return 'bool';
    if (Array.isArray(val)) return 'List<dynamic>';
    if (typeof val === 'object') return 'Map<String, dynamic>';
    return 'dynamic';
  },

  // 2. Flutter Error Stack Trace Diagnostic Analyzer
  analyzeErrorLog: function (logStr) {
    if (!logStr.trim()) {
      return {
        title: 'Ready for Analysis',
        diagnosis: 'Paste a Flutter terminal stack trace or error log above to diagnose.',
        fix: '',
      };
    }

    if (logStr.includes('RenderFlex overflowed')) {
      return {
        title: '⚠️ RenderFlex Pixel Overflow Error',
        diagnosis: 'A Row, Column, or Flex container has child widgets that exceed the available screen space.',
        fix: `Wrap the overflowing widget inside an Expanded, Flexible, or SingleChildScrollView:

// Solution:
SingleChildScrollView(
  child: Column(
    children: [ /* Your widgets */ ],
  ),
)`,
      };
    }

    if (logStr.includes('Null check operator used on a null value')) {
      return {
        title: '⚠️ Null Safety Error (Bang ! Operator Crash)',
        diagnosis: 'You used the ! operator on a variable that evaluated to null at runtime.',
        fix: `Remove the ! operator and handle null safely with default fallbacks:

// Bad:
String name = user.name!;

// Solution:
String name = user.name ?? 'Guest User';`,
      };

    }

    if (logStr.includes('ProviderNotFoundException') || logStr.includes('Could not find the correct Provider')) {

      return {

        title: '⚠️ Provider Context Exception',

        diagnosis: 'The BuildContext passed to Provider.of(context) does not contain the Provider ancestor.',

        fix: `Wrap your widget tree above the context lookup with MultiProvider or ProviderScope:

// Solution:

void main() {

  runApp(

    ProviderScope(
    
      child: const MyApp(),

    ),
  );
}`,
      };
    }

    return {
      title: '🔍 General Flutter Exception Diagnosed',
      diagnosis: 'Inspected stack trace for null safety, layout constraints, and state lifecycle issues.',
      fix: 'Recommendation: Check widget tree context and ensure const constructors are properly scoped.',
    };
  },

  // 3. Generate Material 3 ThemeData
  generateThemeData: function (primaryHex = '#38bdf8') {
    return `import 'package:flutter/material.dart';

final ThemeData customDarkTheme = ThemeData(
  useMaterial3: true,
  brightness: Brightness.dark,
  colorScheme: ColorScheme.fromSeed(
    seedColor: const Color(0xFF38BDF8),
    brightness: Brightness.dark,
    background: const Color(0xFF090D16),
    surface: const Color(0xFF1E293B),
  ),
  scaffoldBackgroundColor: const Color(0xFF090D16),
  cardTheme: CardTheme(
    color: const Color(0xFF1E293B),
    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
  ),
);`;
  },
};





