/* ==========================================================================
   FlutterHub Package Directory — Real Package Data Store
   Sources: pub.dev, Flutter Gems, GitHub
   FREE/PRO status refers ONLY to access on FlutterHub, not the packages themselves.
   All listed packages are open-source / publicly available on pub.dev.
   ========================================================================== */

const PACKAGES_DATA = {

  categories: [
    { id: 'all',              name: 'All Packages',        icon: '📦', color: '#38bdf8' },
    { id: 'state_management', name: 'State Management',    icon: '🔄', color: '#8b5cf6' },
    { id: 'ui',               name: 'UI & Widgets',        icon: '🎨', color: '#ec4899' },
    { id: 'networking',       name: 'Networking & API',    icon: '🌐', color: '#06b6d4' },
    { id: 'firebase',         name: 'Firebase & Backend',  icon: '🔥', color: '#f97316' },
    { id: 'animation',        name: 'Animations',          icon: '✨', color: '#a78bfa' },
    { id: 'storage',          name: 'Storage & Database',  icon: '🗄️', color: '#34d399' },
    { id: 'authentication',   name: 'Authentication',      icon: '🔐', color: '#fbbf24' },
    { id: 'maps',             name: 'Maps & Location',     icon: '🗺️', color: '#22d3ee' },
    { id: 'charts',           name: 'Charts & Data Viz',   icon: '📊', color: '#fb7185' },
    { id: 'media',            name: 'Media & Camera',      icon: '🎬', color: '#c084fc' },
    { id: 'localization',     name: 'Localization & i18n', icon: '🌍', color: '#4ade80' },
    { id: 'dev_tools',        name: 'Developer Tools',     icon: '🛠️', color: '#94a3b8' },
    { id: 'forms',            name: 'Forms & Validation',  icon: '📝', color: '#f472b6' },
    { id: 'testing',          name: 'Testing & QA',        icon: '🧪', color: '#a3e635' },
  ],

  packages: [

    /* ── STATE MANAGEMENT ─────────────────────────────────── */
    {
      id: 'pkg_provider',
      name: 'provider',
      tagline: 'A recommended state management approach by the Flutter team',
      description: 'A wrapper around InheritedWidget to make it easier to use and more reusable. Recommended by the Flutter team for small-to-medium apps and a great stepping stone towards more advanced solutions.',
      category: 'state_management',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/provider',
      githubUrl: 'https://github.com/rrousselGit/provider',
      docsUrl: 'https://pub.dev/documentation/provider/latest/',
      installCmd: 'flutter pub add provider',
      version: '6.1.2',
      likes: 12642,
      pubPoints: 160,
      popularity: 99,
      icon: '🧩',
      iconBg: 'linear-gradient(135deg,#8b5cf6,#6d28d9)',
      tags: ['state','inherited-widget','google','recommended'],
      isPremium: false,
      isFeatured: true,
      features: ['InheritedWidget wrapper', 'Type-safe providers', 'No boilerplate', 'Lazy initialization', 'Testable architecture'],
    },
    {
      id: 'pkg_riverpod',
      name: 'flutter_riverpod',
      tagline: 'A reactive caching and data-binding framework. Provider, but better.',
      description: 'Riverpod is a complete rewrite of the Provider package, addressing most of its limitations. It offers compile-time safety, proper IDE support, testability and a scalable architecture pattern.',
      category: 'state_management',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_riverpod',
      githubUrl: 'https://github.com/rrousselGit/riverpod',
      docsUrl: 'https://riverpod.dev/',
      installCmd: 'flutter pub add flutter_riverpod',
      version: '2.5.1',
      likes: 9841,
      pubPoints: 160,
      popularity: 97,
      icon: '⚡',
      iconBg: 'linear-gradient(135deg,#7c3aed,#4f46e5)',
      tags: ['state','reactive','compile-safe','modern'],
      isPremium: true,
      isFeatured: true,
      features: ['Compile-time safety', 'Auto-dispose providers', 'Code generation support', 'DevTools integration', 'Async providers'],
    },
    {
      id: 'pkg_bloc',
      name: 'flutter_bloc',
      tagline: 'Predictable state management with BLoC design pattern',
      description: 'A predictable state management library that implements the BLoC (Business Logic Component) design pattern for Flutter. Widely used in enterprise applications for strict separation of UI and business logic.',
      category: 'state_management',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_bloc',
      githubUrl: 'https://github.com/felangel/bloc',
      docsUrl: 'https://bloclibrary.dev/',
      installCmd: 'flutter pub add flutter_bloc',
      version: '8.1.6',
      likes: 10920,
      pubPoints: 160,
      popularity: 98,
      icon: '🧱',
      iconBg: 'linear-gradient(135deg,#4f46e5,#7c3aed)',
      tags: ['state','bloc','cubit','enterprise'],
      isPremium: true,
      isFeatured: false,
      features: ['Streams-based', 'Cubit & BLoC APIs', 'BlocObserver', 'HydratedBloc', 'ReplayCubit'],
    },
    {
      id: 'pkg_getx',
      name: 'get',
      tagline: 'Open screens, snackbars, dialogs & more without context in Flutter',
      description: 'GetX is a lightweight, powerful solution for Flutter. It combines high-performance state management, intelligent dependency injection, and route management in a simple and practical way.',
      category: 'state_management',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/get',
      githubUrl: 'https://github.com/jonataslaw/getx',
      docsUrl: 'https://github.com/jonataslaw/getx#readme',
      installCmd: 'flutter pub add get',
      version: '4.6.6',
      likes: 9254,
      pubPoints: 140,
      popularity: 96,
      icon: '🚀',
      iconBg: 'linear-gradient(135deg,#e11d48,#be185d)',
      tags: ['state','routing','di','getx'],
      isPremium: true,
      isFeatured: false,
      features: ['Reactive state management', 'Route management', 'Dependency injection', 'Internationalization', 'Utils'],
    },
    {
      id: 'pkg_mobx',
      name: 'flutter_mobx',
      tagline: 'MobX.dart integration for Flutter — reactive state, made simple',
      description: 'flutter_mobx provides the Observer widget that listens to observables and automatically rebuilds on changes. The MobX approach is transparent and reactive, reducing boilerplate significantly.',
      category: 'state_management',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_mobx',
      githubUrl: 'https://github.com/mobxjs/mobx.dart',
      docsUrl: 'https://mobx.netlify.app/',
      installCmd: 'flutter pub add flutter_mobx',
      version: '2.2.0+1',
      likes: 2310,
      pubPoints: 140,
      popularity: 87,
      icon: '⚛️',
      iconBg: 'linear-gradient(135deg,#b45309,#d97706)',
      tags: ['state','reactive','mobx','observable'],
      isPremium: true,
      isFeatured: false,
      features: ['Observable & Action', 'Computed values', 'Reactions', 'Code generation', 'DevTools'],
    },

    /* ── NETWORKING ──────────────────────────────────────── */
    {
      id: 'pkg_http',
      name: 'http',
      tagline: 'The official composable HTTP client for Dart',
      description: 'A composable, Future-based library for making HTTP requests. This package contains a set of high-level functions and classes that make it easy to consume HTTP resources. It is officially maintained by the Dart team.',
      category: 'networking',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/http',
      githubUrl: 'https://github.com/dart-lang/http',
      docsUrl: 'https://pub.dev/documentation/http/latest/',
      installCmd: 'flutter pub add http',
      version: '1.2.1',
      likes: 9031,
      pubPoints: 160,
      popularity: 99,
      icon: '🌐',
      iconBg: 'linear-gradient(135deg,#0284c7,#0369a1)',
      tags: ['http','networking','dart-team','official'],
      isPremium: false,
      isFeatured: true,
      features: ['GET/POST/PUT/DELETE', 'Future-based API', 'Multipart requests', 'Streaming responses', 'Dart team maintained'],
    },
    {
      id: 'pkg_dio',
      name: 'dio',
      tagline: 'Powerful HTTP client with interceptors, FormData, and cancellation',
      description: 'Dio is a powerful HTTP networking package for Dart/Flutter, supporting global configuration, Interceptors, FormData, request cancellation, file upload/download, timeout, and custom adapters.',
      category: 'networking',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/dio',
      githubUrl: 'https://github.com/cfug/dio',
      docsUrl: 'https://pub.dev/documentation/dio/latest/',
      installCmd: 'flutter pub add dio',
      version: '5.4.3+1',
      likes: 9512,
      pubPoints: 160,
      popularity: 97,
      icon: '⚡',
      iconBg: 'linear-gradient(135deg,#06b6d4,#0891b2)',
      tags: ['http','networking','interceptor','upload'],
      isPremium: true,
      isFeatured: false,
      features: ['Request interceptors', 'Cancellation tokens', 'FormData upload', 'Download progress', 'Global config'],
    },
    {
      id: 'pkg_graphql',
      name: 'graphql_flutter',
      tagline: 'GraphQL client for Flutter with caching and subscriptions',
      description: 'A GraphQL client for Flutter, bringing all the features from a modern GraphQL client: queries, mutations, subscriptions, caching, error handling and more. Integrates with Provider for state.',
      category: 'networking',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/graphql_flutter',
      githubUrl: 'https://github.com/zino-hofmann/graphql-flutter',
      docsUrl: 'https://zino-hofmann.github.io/graphql-flutter',
      installCmd: 'flutter pub add graphql_flutter',
      version: '5.2.0-beta.6',
      likes: 2104,
      pubPoints: 120,
      popularity: 82,
      icon: '◼',
      iconBg: 'linear-gradient(135deg,#e11d48,#be185d)',
      tags: ['graphql','query','mutation','subscription'],
      isPremium: true,
      isFeatured: false,
      features: ['Query & Mutation widgets', 'Subscription support', 'Normalized cache', 'Auth link', 'Error handling'],
    },
    {
      id: 'pkg_retrofit',
      name: 'retrofit',
      tagline: 'Type-safe REST API client generator for Dart, inspired by Retrofit',
      description: 'Retrofit.dart is an HTTP client generator using source_gen and inspired by Retrofit for Java. It works with Dio and generates type-safe client code from annotations.',
      category: 'networking',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/retrofit',
      githubUrl: 'https://github.com/trevorwang/retrofit.dart',
      docsUrl: 'https://pub.dev/documentation/retrofit/latest/',
      installCmd: 'flutter pub add retrofit',
      version: '4.1.0',
      likes: 1543,
      pubPoints: 130,
      popularity: 84,
      icon: '🔌',
      iconBg: 'linear-gradient(135deg,#059669,#047857)',
      tags: ['rest','code-gen','annotation','type-safe'],
      isPremium: true,
      isFeatured: false,
      features: ['Annotation-based', 'Code generation', 'Dio integration', 'JSON serialization', 'Type-safe'],
    },

    /* ── UI & WIDGETS ─────────────────────────────────────── */
    {
      id: 'pkg_flutter_svg',
      name: 'flutter_svg',
      tagline: 'Render SVG files and strings in Flutter widgets',
      description: 'An SVG rendering library for Flutter that uses the Dart SVG specification. Supports most SVG 1.1 and 2.0 features and can render SVG from assets, network, memory, or string.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_svg',
      githubUrl: 'https://github.com/dnfield/flutter_svg',
      docsUrl: 'https://pub.dev/documentation/flutter_svg/latest/',
      installCmd: 'flutter pub add flutter_svg',
      version: '2.0.10+1',
      likes: 7843,
      pubPoints: 160,
      popularity: 98,
      icon: '🎭',
      iconBg: 'linear-gradient(135deg,#ec4899,#be185d)',
      tags: ['svg','vector','graphics','image'],
      isPremium: false,
      isFeatured: true,
      features: ['SVG 1.1 & 2.0 support', 'Asset loading', 'Network SVGs', 'Color filter', 'Null-safe'],
    },
    {
      id: 'pkg_google_fonts',
      name: 'google_fonts',
      tagline: 'Use 1,000+ Google Fonts directly in your Flutter app',
      description: 'The google_fonts package for Flutter allows you to easily use any of the 1,000+ fonts from fonts.google.com in your Flutter app. Fonts are loaded via http on demand and cached in the app\'s file system.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/google_fonts',
      githubUrl: 'https://github.com/material-foundation/flutter-packages/tree/main/packages/google_fonts',
      docsUrl: 'https://pub.dev/documentation/google_fonts/latest/',
      installCmd: 'flutter pub add google_fonts',
      version: '6.2.1',
      likes: 8012,
      pubPoints: 160,
      popularity: 98,
      icon: '🔤',
      iconBg: 'linear-gradient(135deg,#4285f4,#1a73e8)',
      tags: ['fonts','typography','google','ui'],
      isPremium: false,
      isFeatured: true,
      features: ['1000+ fonts', 'Lazy loading', 'Offline caching', 'All Flutter text styles', 'Theme integration'],
    },
    {
      id: 'pkg_cached_network_image',
      name: 'cached_network_image',
      tagline: 'Flutter library to load and cache network images',
      description: 'A flutter library to show images from the internet and keep them in the cache directory. Supports placeholder widgets, error widgets, and animated fade-in.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/cached_network_image',
      githubUrl: 'https://github.com/Baseflow/flutter_cached_network_image',
      docsUrl: 'https://pub.dev/documentation/cached_network_image/latest/',
      installCmd: 'flutter pub add cached_network_image',
      version: '3.3.1',
      likes: 7354,
      pubPoints: 160,
      popularity: 98,
      icon: '🖼️',
      iconBg: 'linear-gradient(135deg,#7c3aed,#6d28d9)',
      tags: ['image','cache','network','placeholder'],
      isPremium: false,
      isFeatured: true,
      features: ['Disk & memory cache', 'Placeholder widget', 'Error widget', 'Fade animation', 'Progress indicator'],
    },
    {
      id: 'pkg_shimmer',
      name: 'shimmer',
      tagline: 'Adds a shimmer loading effect to your Flutter app',
      description: 'A package that provides an easy way to add a shimmer effect to your Flutter app. Perfect for creating skeleton loading screens while data is being fetched.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/shimmer',
      githubUrl: 'https://github.com/hnvn/flutter_shimmer',
      docsUrl: 'https://pub.dev/documentation/shimmer/latest/',
      installCmd: 'flutter pub add shimmer',
      version: '3.0.0',
      likes: 3845,
      pubPoints: 130,
      popularity: 93,
      icon: '✨',
      iconBg: 'linear-gradient(135deg,#f59e0b,#d97706)',
      tags: ['loading','skeleton','shimmer','ux'],
      isPremium: true,
      isFeatured: false,
      features: ['Custom colors', 'Gradient direction', 'Loop control', 'Child widget wrap', 'Lightweight'],
    },
    {
      id: 'pkg_lottie',
      name: 'lottie',
      tagline: 'Render After Effects animations natively in Flutter',
      description: 'Lottie is a mobile library that parses Adobe After Effects animations exported as JSON with Bodymovin and renders them natively on mobile and the web.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/lottie',
      githubUrl: 'https://github.com/xvrh/lottie-flutter',
      docsUrl: 'https://pub.dev/documentation/lottie/latest/',
      installCmd: 'flutter pub add lottie',
      version: '3.1.2',
      likes: 4521,
      pubPoints: 160,
      popularity: 95,
      icon: '🎞️',
      iconBg: 'linear-gradient(135deg,#06b6d4,#0891b2)',
      tags: ['animation','lottie','after-effects','json'],
      isPremium: true,
      isFeatured: false,
      features: ['JSON-based animation', 'Asset & network', 'Animation controller', 'Composition loading', 'Platform-native'],
    },
    {
      id: 'pkg_flutter_staggered_grid',
      name: 'flutter_staggered_grid_view',
      tagline: 'Staggered, masonry & tile grid layouts for Flutter',
      description: 'Provides various staggered grid view layouts for Flutter. Supports masonry grids, aligned grids, staggered grids, and woven grids with full customization.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_staggered_grid_view',
      githubUrl: 'https://github.com/letsar/flutter_staggered_grid_view',
      docsUrl: 'https://pub.dev/documentation/flutter_staggered_grid_view/latest/',
      installCmd: 'flutter pub add flutter_staggered_grid_view',
      version: '0.7.0',
      likes: 3612,
      pubPoints: 130,
      popularity: 91,
      icon: '🔲',
      iconBg: 'linear-gradient(135deg,#ec4899,#db2777)',
      tags: ['grid','masonry','staggered','layout'],
      isPremium: true,
      isFeatured: false,
      features: ['Masonry grid', 'Aligned grid', 'Staggered tiles', 'Woven layout', 'Sliver support'],
    },
    {
      id: 'pkg_flex_color_scheme',
      name: 'flex_color_scheme',
      tagline: 'Theme Flutter apps with Material 3 color schemes easily',
      description: 'FlexColorScheme helps you make beautiful Flutter color scheme based themes, with optional Material 3 support. Use built-in schemes or create your own and apply them with a few lines of code.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flex_color_scheme',
      githubUrl: 'https://github.com/rydmike/flex_color_scheme',
      docsUrl: 'https://docs.flexcolorscheme.com/',
      installCmd: 'flutter pub add flex_color_scheme',
      version: '7.3.1',
      likes: 2831,
      pubPoints: 160,
      popularity: 90,
      icon: '🎨',
      iconBg: 'linear-gradient(135deg,#a855f7,#9333ea)',
      tags: ['theme','material3','color','design-system'],
      isPremium: true,
      isFeatured: false,
      features: ['50+ built-in schemes', 'Material 3 support', 'ThemeData shortcuts', 'Sub-themes', 'Dark mode'],
    },

    /* ── FIREBASE & BACKEND ──────────────────────────────── */
    {
      id: 'pkg_firebase_core',
      name: 'firebase_core',
      tagline: 'Essential Flutter plugin to connect to Firebase services',
      description: 'A Flutter plugin to use the Firebase Core API, which enables connecting to multiple Firebase apps. Required as a dependency by all other Firebase Flutter plugins.',
      category: 'firebase',
      platforms: ['android','ios','web','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/firebase_core',
      githubUrl: 'https://github.com/firebase/flutterfire',
      docsUrl: 'https://firebase.flutter.dev/',
      installCmd: 'flutter pub add firebase_core',
      version: '3.3.0',
      likes: 6123,
      pubPoints: 140,
      popularity: 96,
      icon: '🔥',
      iconBg: 'linear-gradient(135deg,#f97316,#ea580c)',
      tags: ['firebase','google','core','backend'],
      isPremium: true,
      isFeatured: false,
      features: ['Multi-app support', 'Null-safe', 'Web support', 'Platform channels', 'FlutterFire CLI'],
    },
    {
      id: 'pkg_firebase_auth',
      name: 'firebase_auth',
      tagline: 'Firebase Authentication for Flutter — email, Google, Apple & more',
      description: 'A Flutter plugin to use the Firebase Authentication API. Supports email/password, phone, Google, Apple, GitHub, Facebook, Twitter sign-in and anonymous auth.',
      category: 'firebase',
      platforms: ['android','ios','web','macos'],
      pubDevUrl: 'https://pub.dev/packages/firebase_auth',
      githubUrl: 'https://github.com/firebase/flutterfire',
      docsUrl: 'https://firebase.flutter.dev/docs/auth/overview',
      installCmd: 'flutter pub add firebase_auth',
      version: '5.3.0',
      likes: 6004,
      pubPoints: 140,
      popularity: 96,
      icon: '🔐',
      iconBg: 'linear-gradient(135deg,#f97316,#c2410c)',
      tags: ['firebase','auth','google','sign-in'],
      isPremium: true,
      isFeatured: false,
      features: ['Email & password', 'Social sign-in', 'Phone auth', 'Anonymous auth', 'ID token'],
    },
    {
      id: 'pkg_cloud_firestore',
      name: 'cloud_firestore',
      tagline: 'Cloud Firestore NoSQL database Flutter plugin',
      description: 'A Flutter plugin to use the Cloud Firestore API. Cloud Firestore is a flexible, scalable NoSQL cloud database to store and sync data for client- and server-side development.',
      category: 'firebase',
      platforms: ['android','ios','web','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/cloud_firestore',
      githubUrl: 'https://github.com/firebase/flutterfire',
      docsUrl: 'https://firebase.flutter.dev/docs/firestore/overview',
      installCmd: 'flutter pub add cloud_firestore',
      version: '5.4.0',
      likes: 5832,
      pubPoints: 140,
      popularity: 96,
      icon: '☁️',
      iconBg: 'linear-gradient(135deg,#3b82f6,#1d4ed8)',
      tags: ['firebase','firestore','nosql','realtime'],
      isPremium: true,
      isFeatured: false,
      features: ['Real-time listeners', 'Offline support', 'Transactions', 'Batch writes', 'Composite queries'],
    },
    {
      id: 'pkg_firebase_storage',
      name: 'firebase_storage',
      tagline: 'Cloud Storage for Firebase — upload & download files',
      description: 'A Flutter plugin to use Firebase Cloud Storage API. Provides secure file uploads and downloads for Firebase apps, regardless of network quality.',
      category: 'firebase',
      platforms: ['android','ios','web','macos'],
      pubDevUrl: 'https://pub.dev/packages/firebase_storage',
      githubUrl: 'https://github.com/firebase/flutterfire',
      docsUrl: 'https://firebase.flutter.dev/docs/storage/overview',
      installCmd: 'flutter pub add firebase_storage',
      version: '12.3.0',
      likes: 3892,
      pubPoints: 130,
      popularity: 92,
      icon: '🗃️',
      iconBg: 'linear-gradient(135deg,#f59e0b,#b45309)',
      tags: ['firebase','storage','upload','files'],
      isPremium: true,
      isFeatured: false,
      features: ['Upload & download', 'Progress tracking', 'Metadata', 'Security rules', 'Resumable uploads'],
    },
    {
      id: 'pkg_firebase_messaging',
      name: 'firebase_messaging',
      tagline: 'Push notifications via Firebase Cloud Messaging (FCM)',
      description: 'A Flutter plugin to use the Firebase Cloud Messaging (FCM) API. Enables sending notifications and messages to user devices on Android, iOS and Web.',
      category: 'firebase',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/firebase_messaging',
      githubUrl: 'https://github.com/firebase/flutterfire',
      docsUrl: 'https://firebase.flutter.dev/docs/messaging/overview',
      installCmd: 'flutter pub add firebase_messaging',
      version: '15.1.0',
      likes: 4421,
      pubPoints: 130,
      popularity: 93,
      icon: '🔔',
      iconBg: 'linear-gradient(135deg,#f97316,#ea580c)',
      tags: ['push-notifications','fcm','firebase','background'],
      isPremium: true,
      isFeatured: false,
      features: ['Foreground & background', 'Topic subscriptions', 'Data messages', 'Notification click', 'Token refresh'],
    },

    /* ── ANIMATION ───────────────────────────────────────── */
    {
      id: 'pkg_animate_do',
      name: 'animate_do',
      tagline: 'Beautiful animations inspired by Animate.css for Flutter',
      description: 'A collection of beautiful pre-built animations inspired by animate.css. Provides easy-to-use animation widgets like FadeIn, BounceIn, SlideIn, and many more.',
      category: 'animation',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/animate_do',
      githubUrl: 'https://github.com/Klerith/animate_do_package',
      docsUrl: 'https://pub.dev/documentation/animate_do/latest/',
      installCmd: 'flutter pub add animate_do',
      version: '3.3.4',
      likes: 2654,
      pubPoints: 130,
      popularity: 88,
      icon: '🌀',
      iconBg: 'linear-gradient(135deg,#a78bfa,#8b5cf6)',
      tags: ['animation','fade','bounce','slide'],
      isPremium: true,
      isFeatured: false,
      features: ['30+ animations', 'Duration control', 'Delay support', 'Animation controller', 'Infinite loop'],
    },
    {
      id: 'pkg_flutter_animate',
      name: 'flutter_animate',
      tagline: 'A performant library for adding animations to Flutter widgets',
      description: 'flutter_animate adds powerful, easy-to-use animations to Flutter. Chain multiple effects, customize timing, and control animations programmatically with a clean API.',
      category: 'animation',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_animate',
      githubUrl: 'https://github.com/gskinner/flutter_animate',
      docsUrl: 'https://pub.dev/documentation/flutter_animate/latest/',
      installCmd: 'flutter pub add flutter_animate',
      version: '4.5.0',
      likes: 3012,
      pubPoints: 160,
      popularity: 92,
      icon: '🎯',
      iconBg: 'linear-gradient(135deg,#c084fc,#a855f7)',
      tags: ['animation','effects','chain','gskinner'],
      isPremium: true,
      isFeatured: false,
      features: ['Effect chaining', 'Custom effects', 'Adaptive animations', 'Shader support', 'Adapter system'],
    },
    {
      id: 'pkg_rive',
      name: 'rive',
      tagline: 'Use Rive animations in Flutter — real-time interactive graphics',
      description: 'The official Rive Flutter runtime. Rive lets you create interactive animations using its editor, then embed them in Flutter apps as real-time, state machine-driven graphics.',
      category: 'animation',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/rive',
      githubUrl: 'https://github.com/rive-app/rive-flutter',
      docsUrl: 'https://rive.app/docs',
      installCmd: 'flutter pub add rive',
      version: '0.13.11',
      likes: 2943,
      pubPoints: 130,
      popularity: 90,
      icon: '🎬',
      iconBg: 'linear-gradient(135deg,#06b6d4,#0e7490)',
      tags: ['animation','rive','interactive','state-machine'],
      isPremium: true,
      isFeatured: false,
      features: ['State machine animations', 'Artboard API', 'Input triggers', 'Runtime controller', 'Skia backend'],
    },
    {
      id: 'pkg_spring',
      name: 'spring',
      tagline: 'Spring physics simulation animations for Flutter',
      description: 'Spring is a Flutter package that provides spring-based physics simulations for smooth, natural animations. Perfect for bounce effects, elastic transitions and gesture-driven interactions.',
      category: 'animation',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/spring',
      githubUrl: 'https://github.com/KaushickSArgekar/spring',
      docsUrl: 'https://pub.dev/documentation/spring/latest/',
      installCmd: 'flutter pub add spring',
      version: '2.1.0',
      likes: 612,
      pubPoints: 100,
      popularity: 75,
      icon: '🌀',
      iconBg: 'linear-gradient(135deg,#34d399,#059669)',
      tags: ['spring','physics','animation','bounce'],
      isPremium: true,
      isFeatured: false,
      features: ['Spring physics', 'Configurable stiffness', 'Damping control', 'Gesture-driven', 'Lightweight'],
    },

    /* ── STORAGE & DATABASE ───────────────────────────────── */
    {
      id: 'pkg_shared_preferences',
      name: 'shared_preferences',
      tagline: 'Persistent key-value storage for Flutter apps',
      description: 'A Flutter plugin for reading and writing simple key-value pairs. Wraps NSUserDefaults on iOS, SharedPreferences on Android. Perfect for storing user preferences and small amounts of data.',
      category: 'storage',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/shared_preferences',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/shared_preferences',
      docsUrl: 'https://pub.dev/documentation/shared_preferences/latest/',
      installCmd: 'flutter pub add shared_preferences',
      version: '2.3.1',
      likes: 8904,
      pubPoints: 160,
      popularity: 99,
      icon: '💾',
      iconBg: 'linear-gradient(135deg,#34d399,#10b981)',
      tags: ['storage','prefs','key-value','official'],
      isPremium: false,
      isFeatured: true,
      features: ['String/bool/int/double/list', 'Async API', 'Platform native', 'Mock support', 'Null-safe'],
    },
    {
      id: 'pkg_hive',
      name: 'hive_flutter',
      tagline: 'Lightweight & blazing fast key-value NoSQL database',
      description: 'Hive is a lightweight and blazing fast key-value database written in pure Dart. No native dependencies, works on all platforms, supports encryption and adapters for custom objects.',
      category: 'storage',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/hive_flutter',
      githubUrl: 'https://github.com/hivedb/hive',
      docsUrl: 'https://docs.hivedb.dev/',
      installCmd: 'flutter pub add hive_flutter',
      version: '1.1.0',
      likes: 5123,
      pubPoints: 130,
      popularity: 93,
      icon: '🗄️',
      iconBg: 'linear-gradient(135deg,#f59e0b,#d97706)',
      tags: ['database','nosql','local','hive'],
      isPremium: true,
      isFeatured: false,
      features: ['No native deps', 'Strong encryption', 'Type adapters', 'Lazy boxes', 'Pure Dart'],
    },
    {
      id: 'pkg_sqflite',
      name: 'sqflite',
      tagline: 'SQLite plugin for Flutter — Android and iOS',
      description: 'SQLite plugin for Flutter. Supports transactions and batches, automatic version management on open, helpers for insert/query/update/delete queries, and DB operations run in a background thread on iOS and Android.',
      category: 'storage',
      platforms: ['android','ios','macos'],
      pubDevUrl: 'https://pub.dev/packages/sqflite',
      githubUrl: 'https://github.com/tekartik/sqflite',
      docsUrl: 'https://pub.dev/documentation/sqflite/latest/',
      installCmd: 'flutter pub add sqflite',
      version: '2.3.3+1',
      likes: 5621,
      pubPoints: 150,
      popularity: 95,
      icon: '🗃️',
      iconBg: 'linear-gradient(135deg,#3b82f6,#2563eb)',
      tags: ['sql','sqlite','database','local'],
      isPremium: true,
      isFeatured: false,
      features: ['Full SQLite API', 'Batch operations', 'Background thread', 'Raw queries', 'Migrations'],
    },
    {
      id: 'pkg_isar',
      name: 'isar',
      tagline: 'The fastest Flutter database — native, schema-based',
      description: 'Isar is a super fast cross-platform database for Flutter apps. It features a schema-based API, full CRUD support, links/backlinks, full-text search, and reactive queries.',
      category: 'storage',
      platforms: ['android','ios','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/isar',
      githubUrl: 'https://github.com/isar/isar',
      docsUrl: 'https://isar.dev/',
      installCmd: 'flutter pub add isar',
      version: '3.1.0+1',
      likes: 2921,
      pubPoints: 130,
      popularity: 89,
      icon: '⚡',
      iconBg: 'linear-gradient(135deg,#6366f1,#4f46e5)',
      tags: ['database','fast','schema','isar'],
      isPremium: true,
      isFeatured: false,
      features: ['Schema-based', 'Reactive queries', 'Full-text search', 'Links & backlinks', 'Inspector UI'],
    },
    {
      id: 'pkg_path_provider',
      name: 'path_provider',
      tagline: 'Find commonly used filesystem paths on Android, iOS, macOS and more',
      description: 'A Flutter plugin for finding commonly used locations on the filesystem. Supports finding the temp directory, app documents, external storage, and cache directories.',
      category: 'storage',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/path_provider',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/path_provider',
      docsUrl: 'https://pub.dev/documentation/path_provider/latest/',
      installCmd: 'flutter pub add path_provider',
      version: '2.1.4',
      likes: 6842,
      pubPoints: 160,
      popularity: 99,
      icon: '📁',
      iconBg: 'linear-gradient(135deg,#10b981,#059669)',
      tags: ['filesystem','paths','storage','official'],
      isPremium: false,
      isFeatured: false,
      features: ['Temp directory', 'Documents directory', 'Cache directory', 'External storage', 'All platforms'],
    },

    /* ── AUTHENTICATION ──────────────────────────────────── */
    {
      id: 'pkg_google_sign_in',
      name: 'google_sign_in',
      tagline: 'Google Sign-In plugin for Flutter',
      description: 'A Flutter plugin for Google Sign-In, a secure authentication system that reduces the burden of login for your users, by enabling them to sign in with their Google Account.',
      category: 'authentication',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/google_sign_in',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/google_sign_in',
      docsUrl: 'https://pub.dev/documentation/google_sign_in/latest/',
      installCmd: 'flutter pub add google_sign_in',
      version: '6.2.1',
      likes: 5421,
      pubPoints: 150,
      popularity: 95,
      icon: '🔑',
      iconBg: 'linear-gradient(135deg,#4285f4,#1a73e8)',
      tags: ['google','oauth','sign-in','auth'],
      isPremium: true,
      isFeatured: false,
      features: ['OAuth 2.0', 'Silent sign-in', 'Server auth code', 'Web support', 'ID token'],
    },
    {
      id: 'pkg_local_auth',
      name: 'local_auth',
      tagline: 'Biometric authentication — fingerprint, Face ID and PIN',
      description: 'This Flutter plugin provides means to perform local, on-device authentication of the user. Supports fingerprint, Face ID, iris, and device credential fallback.',
      category: 'authentication',
      platforms: ['android','ios','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/local_auth',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/local_auth',
      docsUrl: 'https://pub.dev/documentation/local_auth/latest/',
      installCmd: 'flutter pub add local_auth',
      version: '2.3.0',
      likes: 3842,
      pubPoints: 150,
      popularity: 91,
      icon: '👆',
      iconBg: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
      tags: ['biometric','fingerprint','face-id','auth'],
      isPremium: true,
      isFeatured: false,
      features: ['Fingerprint & Face ID', 'Device credential fallback', 'Availability check', 'Custom dialogs', 'Iris scan'],
    },
    {
      id: 'pkg_flutter_appauth',
      name: 'flutter_appauth',
      tagline: 'OpenID Connect & OAuth 2.0 client for Flutter apps',
      description: 'A Flutter wrapper package around the AppAuth iOS and Android SDKs so it can be used in Flutter apps. Supports authorization code flow with PKCE, token refresh, and end session.',
      category: 'authentication',
      platforms: ['android','ios'],
      pubDevUrl: 'https://pub.dev/packages/flutter_appauth',
      githubUrl: 'https://github.com/MaikuB/flutter_appauth',
      docsUrl: 'https://pub.dev/documentation/flutter_appauth/latest/',
      installCmd: 'flutter pub add flutter_appauth',
      version: '7.0.1',
      likes: 1032,
      pubPoints: 120,
      popularity: 81,
      icon: '🔓',
      iconBg: 'linear-gradient(135deg,#06b6d4,#0284c7)',
      tags: ['oidc','oauth','appauth','pkce'],
      isPremium: true,
      isFeatured: false,
      features: ['PKCE support', 'Token refresh', 'End session', 'Custom tabs', 'OIDC discovery'],
    },

    /* ── MAPS & LOCATION ─────────────────────────────────── */
    {
      id: 'pkg_google_maps',
      name: 'google_maps_flutter',
      tagline: 'Official Google Maps plugin for Flutter',
      description: 'A Flutter plugin that provides a Google Maps widget. The plugin uses the native Google Maps SDK on iOS and Android and exposes a unified Flutter API.',
      category: 'maps',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/google_maps_flutter',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/google_maps_flutter',
      docsUrl: 'https://pub.dev/documentation/google_maps_flutter/latest/',
      installCmd: 'flutter pub add google_maps_flutter',
      version: '2.9.0',
      likes: 5023,
      pubPoints: 140,
      popularity: 95,
      icon: '🗺️',
      iconBg: 'linear-gradient(135deg,#22c55e,#16a34a)',
      tags: ['maps','google','location','markers'],
      isPremium: true,
      isFeatured: false,
      features: ['Markers & polylines', 'Camera control', 'Info windows', 'Custom tiles', 'Clustering'],
    },
    {
      id: 'pkg_geolocator',
      name: 'geolocator',
      tagline: 'Easy access to device GPS and location services',
      description: 'A Flutter geolocation plugin providing easy access to platform specific location services. Provides methods to retrieve the current location, stream location updates, get last known location, and check permissions.',
      category: 'maps',
      platforms: ['android','ios','web','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/geolocator',
      githubUrl: 'https://github.com/Baseflow/flutter-geolocator',
      docsUrl: 'https://pub.dev/documentation/geolocator/latest/',
      installCmd: 'flutter pub add geolocator',
      version: '12.0.0',
      likes: 5431,
      pubPoints: 160,
      popularity: 96,
      icon: '📍',
      iconBg: 'linear-gradient(135deg,#ef4444,#dc2626)',
      tags: ['gps','location','geolocation','permission'],
      isPremium: true,
      isFeatured: false,
      features: ['Current position', 'Location stream', 'Permission handling', 'Distance calculation', 'Background location'],
    },
    {
      id: 'pkg_flutter_map',
      name: 'flutter_map',
      tagline: 'Open-source map widget using OpenStreetMap — no API key needed',
      description: 'flutter_map is a Dart implementation of Leaflet for Flutter. It works with any map provider, not just Google Maps, and is fully open source with OSM tiles supported out of the box.',
      category: 'maps',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_map',
      githubUrl: 'https://github.com/fleaflet/flutter_map',
      docsUrl: 'https://docs.fleaflet.dev/',
      installCmd: 'flutter pub add flutter_map',
      version: '7.0.2',
      likes: 2831,
      pubPoints: 150,
      popularity: 88,
      icon: '🗺️',
      iconBg: 'linear-gradient(135deg,#0ea5e9,#0284c7)',
      tags: ['osm','leaflet','maps','open-source'],
      isPremium: true,
      isFeatured: false,
      features: ['OpenStreetMap tiles', 'Markers & polygons', 'Custom layers', 'No API key', 'All platforms'],
    },

    /* ── CHARTS & DATA VIZ ───────────────────────────────── */
    {
      id: 'pkg_fl_chart',
      name: 'fl_chart',
      tagline: 'A powerful Flutter chart library with beautiful built-in charts',
      description: 'fl_chart is a highly customizable Flutter chart library that supports Line Charts, Bar Charts, Pie Charts, Scatter Charts and Radar Charts. All charts support animation and touch interaction.',
      category: 'charts',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/fl_chart',
      githubUrl: 'https://github.com/imaNNeo/fl_chart',
      docsUrl: 'https://pub.dev/documentation/fl_chart/latest/',
      installCmd: 'flutter pub add fl_chart',
      version: '0.68.0',
      likes: 5841,
      pubPoints: 160,
      popularity: 96,
      icon: '📊',
      iconBg: 'linear-gradient(135deg,#fb7185,#e11d48)',
      tags: ['charts','graph','line','bar','pie'],
      isPremium: true,
      isFeatured: false,
      features: ['Line & Bar charts', 'Pie & Radar', 'Scatter chart', 'Touch interactions', 'Customizable'],
    },
    {
      id: 'pkg_syncfusion_charts',
      name: 'syncfusion_flutter_charts',
      tagline: 'Feature-rich charts for enterprise Flutter applications',
      description: 'Syncfusion Flutter Charts is a data visualization library written natively in Dart for creating beautiful, animated, and high-performance charts for Flutter mobile and web applications.',
      category: 'charts',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/syncfusion_flutter_charts',
      githubUrl: 'https://github.com/syncfusion/flutter-widgets',
      docsUrl: 'https://help.syncfusion.com/flutter/chart/getting-started',
      installCmd: 'flutter pub add syncfusion_flutter_charts',
      version: '26.2.14',
      likes: 1932,
      pubPoints: 130,
      popularity: 83,
      icon: '📈',
      iconBg: 'linear-gradient(135deg,#3b82f6,#2563eb)',
      tags: ['enterprise','charts','syncfusion','data-viz'],
      isPremium: true,
      isFeatured: false,
      features: ['30+ chart types', 'Technical indicators', 'Zoom & pan', 'Trendlines', 'Export'],
    },

    /* ── MEDIA & CAMERA ──────────────────────────────────── */
    {
      id: 'pkg_image_picker',
      name: 'image_picker',
      tagline: 'Pick images and videos from device gallery or camera',
      description: 'A Flutter plugin for iOS and Android for picking images and videos from the image library, and taking new pictures with the camera. Supports both single and multiple selections.',
      category: 'media',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/image_picker',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/image_picker',
      docsUrl: 'https://pub.dev/documentation/image_picker/latest/',
      installCmd: 'flutter pub add image_picker',
      version: '1.1.2',
      likes: 7023,
      pubPoints: 150,
      popularity: 98,
      icon: '📷',
      iconBg: 'linear-gradient(135deg,#c084fc,#a855f7)',
      tags: ['image','camera','gallery','media'],
      isPremium: true,
      isFeatured: false,
      features: ['Gallery & camera', 'Multiple selection', 'Image quality', 'Video support', 'Web support'],
    },
    {
      id: 'pkg_video_player',
      name: 'video_player',
      tagline: 'Play back video on Android, iOS, and Web',
      description: 'A Flutter plugin for displaying inline video with other Flutter widgets. Supports local assets, network URLs, and multiple video formats. Official package by the Flutter team.',
      category: 'media',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/video_player',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/video_player',
      docsUrl: 'https://pub.dev/documentation/video_player/latest/',
      installCmd: 'flutter pub add video_player',
      version: '2.9.2',
      likes: 5634,
      pubPoints: 150,
      popularity: 96,
      icon: '▶️',
      iconBg: 'linear-gradient(135deg,#ef4444,#dc2626)',
      tags: ['video','player','media','official'],
      isPremium: true,
      isFeatured: false,
      features: ['Local & network', 'Playback control', 'Speed control', 'Looping', 'Subtitles support'],
    },
    {
      id: 'pkg_just_audio',
      name: 'just_audio',
      tagline: 'A rich audio player for Flutter with platform-native playback',
      description: 'A rich, feature-complete audio player for Android, iOS, macOS, web, Linux and Windows. Supports playlists, looping, clipping, shuffling, gapless playback, and background audio.',
      category: 'media',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/just_audio',
      githubUrl: 'https://github.com/ryanheise/just_audio',
      docsUrl: 'https://pub.dev/documentation/just_audio/latest/',
      installCmd: 'flutter pub add just_audio',
      version: '0.9.40',
      likes: 3821,
      pubPoints: 140,
      popularity: 92,
      icon: '🎵',
      iconBg: 'linear-gradient(135deg,#8b5cf6,#7c3aed)',
      tags: ['audio','music','player','background'],
      isPremium: true,
      isFeatured: false,
      features: ['Playlists', 'Gapless playback', 'Background audio', 'Clipping & speed', 'Shuffle & loop'],
    },
    {
      id: 'pkg_camera',
      name: 'camera',
      tagline: 'Control the device camera for photo and video capture',
      description: 'A Flutter plugin for iOS and Android allowing access to the device cameras. Supports preview streams, capturing images and video, flash control, exposure, zoom, and focus modes.',
      category: 'media',
      platforms: ['android','ios','web'],
      pubDevUrl: 'https://pub.dev/packages/camera',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/camera',
      docsUrl: 'https://pub.dev/documentation/camera/latest/',
      installCmd: 'flutter pub add camera',
      version: '0.11.0+2',
      likes: 4023,
      pubPoints: 130,
      popularity: 92,
      icon: '📸',
      iconBg: 'linear-gradient(135deg,#1e293b,#334155)',
      tags: ['camera','capture','photo','video'],
      isPremium: true,
      isFeatured: false,
      features: ['Live preview', 'Photo capture', 'Video recording', 'Flash control', 'Exposure & focus'],
    },

    /* ── LOCALIZATION ─────────────────────────────────────── */
    {
      id: 'pkg_intl',
      name: 'intl',
      tagline: 'Internationalization and localization support for Dart and Flutter',
      description: 'Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.',
      category: 'localization',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/intl',
      githubUrl: 'https://github.com/dart-lang/i18n',
      docsUrl: 'https://pub.dev/documentation/intl/latest/',
      installCmd: 'flutter pub add intl',
      version: '0.19.0',
      likes: 7123,
      pubPoints: 160,
      popularity: 99,
      icon: '🌍',
      iconBg: 'linear-gradient(135deg,#4ade80,#22c55e)',
      tags: ['i18n','l10n','date','number','plurals'],
      isPremium: false,
      isFeatured: false,
      features: ['Message translation', 'Plurals & genders', 'Date formatting', 'Number formatting', 'BiDi text'],
    },
    {
      id: 'pkg_easy_localization',
      name: 'easy_localization',
      tagline: 'Easy and fast localization for your Flutter app',
      description: 'easy_localization simplifies adding multiple language support to Flutter apps using JSON/CSV/YAML files. Supports pluralization, gender, arguments, and RTL.',
      category: 'localization',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/easy_localization',
      githubUrl: 'https://github.com/aissat/easy_localization',
      docsUrl: 'https://pub.dev/documentation/easy_localization/latest/',
      installCmd: 'flutter pub add easy_localization',
      version: '3.0.7',
      likes: 3421,
      pubPoints: 130,
      popularity: 91,
      icon: '🌐',
      iconBg: 'linear-gradient(135deg,#10b981,#059669)',
      tags: ['localization','i18n','json','rtl'],
      isPremium: true,
      isFeatured: false,
      features: ['JSON/CSV/YAML', 'Pluralization', 'RTL support', 'Gender forms', 'Fallback locale'],
    },

    /* ── DEVELOPER TOOLS ─────────────────────────────────── */
    {
      id: 'pkg_logger',
      name: 'logger',
      tagline: 'Small, easy to use, extensible logger with pretty print',
      description: 'Logger is a small logging library in Dart with pretty printing support and various log levels. Output can be customized with custom printers and filters.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/logger',
      githubUrl: 'https://github.com/leisim/logger',
      docsUrl: 'https://pub.dev/documentation/logger/latest/',
      installCmd: 'flutter pub add logger',
      version: '2.4.0',
      likes: 3421,
      pubPoints: 130,
      popularity: 91,
      icon: '📋',
      iconBg: 'linear-gradient(135deg,#64748b,#475569)',
      tags: ['logging','debug','developer','tools'],
      isPremium: true,
      isFeatured: false,
      features: ['Log levels', 'Pretty printing', 'Custom output', 'File logging', 'ANSI colors'],
    },
    {
      id: 'pkg_freezed',
      name: 'freezed',
      tagline: 'Code generation for immutable classes with unions/pattern-matching',
      description: 'Freezed is a code generator for unions/pattern-matching/copy in Dart. It helps to generate immutable model classes with no boilerplate, copyWith, equality, and factory constructors.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/freezed',
      githubUrl: 'https://github.com/rrousselGit/freezed',
      docsUrl: 'https://pub.dev/documentation/freezed/latest/',
      installCmd: 'flutter pub add freezed_annotation\nflutter pub add --dev freezed build_runner',
      version: '2.5.7',
      likes: 5841,
      pubPoints: 160,
      popularity: 96,
      icon: '❄️',
      iconBg: 'linear-gradient(135deg,#38bdf8,#0ea5e9)',
      tags: ['codegen','immutable','union','freezed'],
      isPremium: true,
      isFeatured: false,
      features: ['Immutable classes', 'copyWith generation', 'Union types', 'Pattern matching', 'JSON support'],
    },
    {
      id: 'pkg_json_serializable',
      name: 'json_serializable',
      tagline: 'Automatically generate JSON serialization code for Dart',
      description: 'Provides Dart Build System builders for handling JSON by generating code for fromJson and toJson methods. Works with build_runner to generate serialization code.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/json_serializable',
      githubUrl: 'https://github.com/google/json_serializable.dart',
      docsUrl: 'https://pub.dev/documentation/json_serializable/latest/',
      installCmd: 'flutter pub add json_annotation\nflutter pub add --dev json_serializable build_runner',
      version: '6.8.0',
      likes: 6012,
      pubPoints: 160,
      popularity: 97,
      icon: '⚙️',
      iconBg: 'linear-gradient(135deg,#f59e0b,#b45309)',
      tags: ['json','codegen','serialization','google'],
      isPremium: true,
      isFeatured: false,
      features: ['fromJson & toJson', 'Null safety', 'Custom converters', 'Generics support', 'Build runner'],
    },
    {
      id: 'pkg_flutter_dotenv',
      name: 'flutter_dotenv',
      tagline: 'Load environment variables from a .env file in Flutter',
      description: 'Easily configure any Flutter application with global variables using a .env file. Supports loading from assets, custom filenames, and optional variables.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_dotenv',
      githubUrl: 'https://github.com/java-james/flutter_dotenv',
      docsUrl: 'https://pub.dev/documentation/flutter_dotenv/latest/',
      installCmd: 'flutter pub add flutter_dotenv',
      version: '5.2.1',
      likes: 1254,
      pubPoints: 120,
      popularity: 83,
      icon: '🔧',
      iconBg: 'linear-gradient(135deg,#6b7280,#4b5563)',
      tags: ['env','config','dotenv','secrets'],
      isPremium: true,
      isFeatured: false,
      features: ['.env file loading', 'Optional variables', 'Default values', 'Asset-based', 'Type conversion'],
    },
    {
      id: 'pkg_get_it',
      name: 'get_it',
      tagline: 'Simple service locator / dependency injection for Dart & Flutter',
      description: 'GetIt is a simple service locator for Dart and Flutter that can be used as an IoC container. It allows you to register factories, singletons, and lazy singletons.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/get_it',
      githubUrl: 'https://github.com/fluttercommunity/get_it',
      docsUrl: 'https://pub.dev/documentation/get_it/latest/',
      installCmd: 'flutter pub add get_it',
      version: '8.0.2',
      likes: 4832,
      pubPoints: 160,
      popularity: 95,
      icon: '🔗',
      iconBg: 'linear-gradient(135deg,#6366f1,#4f46e5)',
      tags: ['di','service-locator','ioc','singleton'],
      isPremium: true,
      isFeatured: false,
      features: ['Factories & singletons', 'Async registration', 'Scope management', 'Named instances', 'Reset support'],
    },

    /* ── FORMS & VALIDATION ──────────────────────────────── */
    {
      id: 'pkg_reactive_forms',
      name: 'reactive_forms',
      tagline: 'Model-driven reactive forms for Flutter, inspired by Angular',
      description: 'An Angular-inspired approach to handling forms in Flutter by using the model-driven approach to implement forms. Provides FormGroup, FormControl, validators, and async validators.',
      category: 'forms',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/reactive_forms',
      githubUrl: 'https://github.com/artflutter/reactive_forms',
      docsUrl: 'https://pub.dev/documentation/reactive_forms/latest/',
      installCmd: 'flutter pub add reactive_forms',
      version: '17.0.1',
      likes: 1234,
      pubPoints: 140,
      popularity: 84,
      icon: '📝',
      iconBg: 'linear-gradient(135deg,#f472b6,#ec4899)',
      tags: ['forms','validation','reactive','angular'],
      isPremium: true,
      isFeatured: false,
      features: ['FormGroup & FormControl', 'Built-in validators', 'Async validation', 'Cross-field validation', 'Reactive streams'],
    },
    {
      id: 'pkg_flutter_form_builder',
      name: 'flutter_form_builder',
      tagline: 'Easy-to-use form building kit with built-in validators',
      description: 'This package helps in creation of data collection forms in Flutter by providing the ability to create customized form fields, validate, react to changes, and collect final user input.',
      category: 'forms',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_form_builder',
      githubUrl: 'https://github.com/flutter-form-builder-ecosystem/flutter_form_builder',
      docsUrl: 'https://pub.dev/documentation/flutter_form_builder/latest/',
      installCmd: 'flutter pub add flutter_form_builder',
      version: '9.3.0',
      likes: 2312,
      pubPoints: 140,
      popularity: 88,
      icon: '📄',
      iconBg: 'linear-gradient(135deg,#ec4899,#db2777)',
      tags: ['forms','input','validation','builder'],
      isPremium: true,
      isFeatured: false,
      features: ['Built-in field types', 'Custom validators', 'Group save', 'File picker field', 'Date range field'],
    },

    /* ── TESTING ──────────────────────────────────────────── */
    {
      id: 'pkg_mockito',
      name: 'mockito',
      tagline: 'Dart mocking library — write better unit tests for Flutter',
      description: 'Mockito is a popular Dart mocking framework inspired by Mockito for Java. Use it to create mock objects and stub methods in your unit tests.',
      category: 'testing',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/mockito',
      githubUrl: 'https://github.com/dart-lang/mockito',
      docsUrl: 'https://pub.dev/documentation/mockito/latest/',
      installCmd: 'flutter pub add --dev mockito build_runner',
      version: '5.4.4',
      likes: 3421,
      pubPoints: 160,
      popularity: 93,
      icon: '🧪',
      iconBg: 'linear-gradient(135deg,#a3e635,#65a30d)',
      tags: ['testing','mock','unit-test','dart-team'],
      isPremium: true,
      isFeatured: false,
      features: ['Generated mocks', 'Stubbing & verification', 'Null safety', 'Argument matchers', 'Spy objects'],
    },
    {
      id: 'pkg_integration_test',
      name: 'integration_test',
      tagline: 'Official Flutter integration testing framework',
      description: 'The integration_test plugin enables self-driving testing of Flutter code on devices and emulators. It is the official framework for end-to-end testing of Flutter apps.',
      category: 'testing',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/integration_test',
      githubUrl: 'https://github.com/flutter/flutter',
      docsUrl: 'https://docs.flutter.dev/testing/integration-tests',
      installCmd: 'flutter pub add --dev integration_test',
      version: '1.3.0',
      likes: 2012,
      pubPoints: 140,
      popularity: 87,
      icon: '🔬',
      iconBg: 'linear-gradient(135deg,#4ade80,#16a34a)',
      tags: ['testing','e2e','integration','official'],
      isPremium: true,
      isFeatured: false,
      features: ['End-to-end tests', 'Device testing', 'Screenshot capture', 'Performance profiling', 'CI/CD ready'],
    },

    /* ── MORE UI ──────────────────────────────────────────── */
    {
      id: 'pkg_flutter_slidable',
      name: 'flutter_slidable',
      tagline: 'Slidable list item widget with directional slide actions',
      description: 'A Flutter implementation of slidable list item with directional slide actions that can be dismissed. Perfect for delete/archive actions on list items.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_slidable',
      githubUrl: 'https://github.com/letsar/flutter_slidable',
      docsUrl: 'https://pub.dev/documentation/flutter_slidable/latest/',
      installCmd: 'flutter pub add flutter_slidable',
      version: '3.1.1',
      likes: 4021,
      pubPoints: 140,
      popularity: 93,
      icon: '↔️',
      iconBg: 'linear-gradient(135deg,#06b6d4,#0891b2)',
      tags: ['swipe','gesture','list','slidable'],
      isPremium: true,
      isFeatured: false,
      features: ['Left & right actions', 'Dismiss support', 'Custom motion', 'ActionPane', 'Dismissible'],
    },
    {
      id: 'pkg_pull_to_refresh',
      name: 'easy_refresh',
      tagline: 'Pull-to-refresh and load-more for Flutter lists and grids',
      description: 'easy_refresh provides a pull-to-refresh and load-more for Flutter widgets. Supports list, grid, and custom scroll views with customizable indicators.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/easy_refresh',
      githubUrl: 'https://github.com/xuelongqy/flutter_easy_refresh',
      docsUrl: 'https://pub.dev/documentation/easy_refresh/latest/',
      installCmd: 'flutter pub add easy_refresh',
      version: '3.4.0',
      likes: 1832,
      pubPoints: 130,
      popularity: 85,
      icon: '🔄',
      iconBg: 'linear-gradient(135deg,#10b981,#059669)',
      tags: ['refresh','pull','list','pagination'],
      isPremium: true,
      isFeatured: false,
      features: ['Pull to refresh', 'Load more', 'Custom indicators', 'Nested scroll', 'Spring animation'],
    },
    {
      id: 'pkg_flutter_rating_bar',
      name: 'flutter_rating_bar',
      tagline: 'Customizable, animated star rating widget for Flutter',
      description: 'A simple yet fully customizable Rating Bar for flutter. Also known as a Star Rating. Supports half ratings, fractional ratings, custom icons and animated rating changes.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/flutter_rating_bar',
      githubUrl: 'https://github.com/sarbagyastha/flutter_rating_bar',
      docsUrl: 'https://pub.dev/documentation/flutter_rating_bar/latest/',
      installCmd: 'flutter pub add flutter_rating_bar',
      version: '4.0.1',
      likes: 2842,
      pubPoints: 130,
      popularity: 90,
      icon: '⭐',
      iconBg: 'linear-gradient(135deg,#fbbf24,#f59e0b)',
      tags: ['rating','stars','review','widget'],
      isPremium: true,
      isFeatured: false,
      features: ['Half & fractional', 'Custom icons', 'Indicator mode', 'RTL support', 'Animated'],
    },
    {
      id: 'pkg_pinput',
      name: 'pinput',
      tagline: 'Beautiful and highly customizable OTP/PIN input field',
      description: 'Pinput is a Flutter package that provides a beautiful, highly customizable pin input field widget. Perfect for OTP verification screens.',
      category: 'ui',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/pinput',
      githubUrl: 'https://github.com/Tkko/Flutter_Pinput',
      docsUrl: 'https://pub.dev/documentation/pinput/latest/',
      installCmd: 'flutter pub add pinput',
      version: '5.0.0',
      likes: 2234,
      pubPoints: 140,
      popularity: 89,
      icon: '🔢',
      iconBg: 'linear-gradient(135deg,#f472b6,#db2777)',
      tags: ['otp','pin','input','verification'],
      isPremium: true,
      isFeatured: false,
      features: ['Custom pin theme', 'Cursor support', 'Auto-fill', 'Error states', 'Animation'],
    },
    {
      id: 'pkg_url_launcher',
      name: 'url_launcher',
      tagline: 'Launch URLs in the mobile platform from Flutter apps',
      description: 'A Flutter plugin for launching a URL. Supports web, phone, email, and custom URL schemes. Officially maintained by the Flutter team.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/url_launcher',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/url_launcher',
      docsUrl: 'https://pub.dev/documentation/url_launcher/latest/',
      installCmd: 'flutter pub add url_launcher',
      version: '6.3.0',
      likes: 7234,
      pubPoints: 160,
      popularity: 99,
      icon: '🔗',
      iconBg: 'linear-gradient(135deg,#0ea5e9,#0284c7)',
      tags: ['url','browser','launch','official'],
      isPremium: true,
      isFeatured: false,
      features: ['HTTP/HTTPS', 'Email intent', 'Phone calls', 'Custom schemes', 'In-app browser'],
    },
    {
      id: 'pkg_permission_handler',
      name: 'permission_handler',
      tagline: 'Permission plugin for Flutter — request & check platform permissions',
      description: 'This plugin provides a cross-platform API to request and check permissions on iOS and Android. Handles camera, microphone, location, storage, notification, and many more permissions.',
      category: 'dev_tools',
      platforms: ['android','ios','macos','windows'],
      pubDevUrl: 'https://pub.dev/packages/permission_handler',
      githubUrl: 'https://github.com/Baseflow/flutter-permission-handler',
      docsUrl: 'https://pub.dev/documentation/permission_handler/latest/',
      installCmd: 'flutter pub add permission_handler',
      version: '11.3.1',
      likes: 5423,
      pubPoints: 150,
      popularity: 95,
      icon: '🔐',
      iconBg: 'linear-gradient(135deg,#f59e0b,#d97706)',
      tags: ['permissions','camera','location','notification'],
      isPremium: true,
      isFeatured: false,
      features: ['40+ permissions', 'Rationale dialog', 'Settings redirect', 'Status checking', 'Batch request'],
    },
    {
      id: 'pkg_connectivity_plus',
      name: 'connectivity_plus',
      tagline: 'Check network connectivity status in Flutter apps',
      description: 'This plugin allows Flutter apps to discover network connectivity and configure themselves accordingly. It can distinguish between cellular and WiFi connections and listens to changes.',
      category: 'networking',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/connectivity_plus',
      githubUrl: 'https://github.com/fluttercommunity/plus_plugins/tree/main/packages/connectivity_plus',
      docsUrl: 'https://pub.dev/documentation/connectivity_plus/latest/',
      installCmd: 'flutter pub add connectivity_plus',
      version: '6.0.5',
      likes: 3821,
      pubPoints: 140,
      popularity: 93,
      icon: '📶',
      iconBg: 'linear-gradient(135deg,#22c55e,#16a34a)',
      tags: ['connectivity','network','wifi','status'],
      isPremium: true,
      isFeatured: false,
      features: ['WiFi & cellular', 'Stream listening', 'VPN detection', 'None state', 'All platforms'],
    },
    {
      id: 'pkg_flutter_secure_storage',
      name: 'flutter_secure_storage',
      tagline: 'Store data securely using Keychain & Keystore',
      description: 'A Flutter plugin to store data in secure storage. Uses Keychain on iOS/macOS, EncryptedSharedPreferences on Android, libsecret on Linux, and Credential Manager on Windows.',
      category: 'storage',
      platforms: ['android','ios','macos','windows','linux','web'],
      pubDevUrl: 'https://pub.dev/packages/flutter_secure_storage',
      githubUrl: 'https://github.com/mogol/flutter_secure_storage',
      docsUrl: 'https://pub.dev/documentation/flutter_secure_storage/latest/',
      installCmd: 'flutter pub add flutter_secure_storage',
      version: '9.2.2',
      likes: 4012,
      pubPoints: 140,
      popularity: 93,
      icon: '🔒',
      iconBg: 'linear-gradient(135deg,#ef4444,#b91c1c)',
      tags: ['security','keychain','storage','encrypted'],
      isPremium: true,
      isFeatured: false,
      features: ['Keychain & Keystore', 'Encrypted storage', 'Read/write/delete', 'All platforms', 'Biometric lock'],
    },
    {
      id: 'pkg_auto_route',
      name: 'auto_route',
      tagline: 'Type-safe routing solution with code generation for Flutter',
      description: 'AutoRoute is a Flutter navigation package that allows for strongly-typed arguments passing, effortless deep-linking, and code generation to eliminate common routing errors.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/auto_route',
      githubUrl: 'https://github.com/Milad-Akarie/auto_route_library',
      docsUrl: 'https://pub.dev/documentation/auto_route/latest/',
      installCmd: 'flutter pub add auto_route\nflutter pub add --dev auto_route_generator build_runner',
      version: '9.2.2',
      likes: 3621,
      pubPoints: 140,
      popularity: 91,
      icon: '🛣️',
      iconBg: 'linear-gradient(135deg,#6366f1,#8b5cf6)',
      tags: ['routing','navigation','code-gen','deep-link'],
      isPremium: true,
      isFeatured: false,
      features: ['Type-safe routing', 'Deep linking', 'Route guards', 'Nested navigation', 'Code generation'],
    },
    {
      id: 'pkg_go_router',
      name: 'go_router',
      tagline: 'Declarative routing for Flutter using the Router API',
      description: 'The go_router package implements the same navigation stack as Navigator but using a URL-based API. It supports deep linking, nested routing, and type-safe parameters.',
      category: 'dev_tools',
      platforms: ['android','ios','web','macos','windows','linux'],
      pubDevUrl: 'https://pub.dev/packages/go_router',
      githubUrl: 'https://github.com/flutter/packages/tree/main/packages/go_router',
      docsUrl: 'https://pub.dev/documentation/go_router/latest/',
      installCmd: 'flutter pub add go_router',
      version: '14.2.7',
      likes: 5021,
      pubPoints: 160,
      popularity: 96,
      icon: '🗺️',
      iconBg: 'linear-gradient(135deg,#0284c7,#0369a1)',
      tags: ['routing','navigation','url','official'],
      isPremium: true,
      isFeatured: false,
      features: ['URL-based routing', 'Deep linking', 'Route guards', 'Shell routes', 'Type-safe params'],
    },

  ]
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = PACKAGES_DATA;
}
