/* ==========================================================================
   FlutterHub Backend — Real Flutter/Dart Package Directory Data Store
   Sources: pub.dev, official Flutter packages, GitHub
   ========================================================================== */

const PACKAGE_CATEGORIES = [
  { id: 'all',              name: 'All Packages',        icon: '📦', color: '#38bdf8' },
  { id: 'state_management', name: 'State Management',    icon: '🔄', color: '#8b5cf6' },
  { id: 'ui',               name: 'UI & Widgets',        icon: '🎨', color: '#ec4899' },
  { id: 'networking',       name: 'Networking & API',    icon: '🌐', color: '#06b6d4' },
  { id: 'firebase',         name: 'Firebase & Backend',  icon: '🔥', color: '#f97316' },
  { id: 'animation',        name: 'Animations',          icon: '✨', color: '#a78bfa' },
  { id: 'storage',          name: 'Storage & Database',  icon: '🗄️', color: '#34d399' },
  { id: 'authentication',   name: 'Authentication',      icon: '🔐', color: '#fbbf24' },
  { id: 'maps',             name: 'Maps & Location',     icon: '🗺️', color: '#22d3ee' },
  { id: 'charts',           name: 'Charts & Data Viz',   icon: '📊', color: '#fb7185' },
  { id: 'media',            name: 'Media & Camera',      icon: '🎬', color: '#c084fc' },
  { id: 'localization',     name: 'Localization & i18n', icon: '🌍', color: '#4ade80' },
  { id: 'dev_tools',        name: 'Developer Tools',     icon: '🛠️', color: '#94a3b8' },
  { id: 'forms',            name: 'Forms & Validation',  icon: '📝', color: '#f472b6' },
  { id: 'testing',          name: 'Testing & QA',        icon: '🧪', color: '#a3e635' },
];

const PACKAGES = [
  /* ── 8 FREE PACKAGES (Available to all users) ───────────────────── */
  {
    id: 'provider',
    name: 'provider',
    publisher: 'dash-overflow.net',
    tagline: 'A recommended state management approach by the Flutter team',
    description: 'A wrapper around InheritedWidget to make it easier to use and more reusable. Recommended by Google for clean, reactive state management in Flutter applications.',
    category: 'state_management',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/provider',
    githubUrl: 'https://github.com/rrousselGit/provider',
    docsUrl: 'https://pub.dev/documentation/provider/latest/',
    installCmd: 'flutter pub add provider',
    version: '6.1.2',
    likes: 12642,
    pubPoints: 160,
    popularity: 99,
    downloads: '5.2M',
    icon: '🧩',
    iconBg: 'linear-gradient(135deg,#8b5cf6,#6d28d9)',
    tags: ['state', 'inheritedwidget', 'google', 'reactive'],
    isPremium: false,
    isFeatured: true,
    features: ['InheritedWidget wrapper', 'Type-safe dependency injection', 'Automatic disposal', 'DevTools inspector integration', 'Zero boilerplate'],
  },
  {
    id: 'http',
    name: 'http',
    publisher: 'dart.dev',
    tagline: 'The official composable HTTP client for Dart and Flutter',
    description: 'A composable, Future-based library for making HTTP requests. Maintained officially by the Dart team with support for GET, POST, PUT, DELETE, and streaming requests.',
    category: 'networking',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/http',
    githubUrl: 'https://github.com/dart-lang/http',
    docsUrl: 'https://pub.dev/documentation/http/latest/',
    installCmd: 'flutter pub add http',
    version: '1.2.1',
    likes: 9031,
    pubPoints: 160,
    popularity: 99,
    downloads: '8.4M',
    icon: '🌐',
    iconBg: 'linear-gradient(135deg,#0284c7,#0369a1)',
    tags: ['http', 'network', 'dart-team', 'rest-api'],
    isPremium: false,
    isFeatured: true,
    features: ['REST API Client', 'Multipart Form uploads', 'Streaming responses', 'Custom HTTP client adapters', 'Native platform performance'],
  },
  {
    id: 'shared_preferences',
    name: 'shared_preferences',
    publisher: 'flutter.dev',
    tagline: 'Persistent key-value storage for Flutter apps',
    description: 'A Flutter plugin for reading and writing simple key-value pairs asynchronously. Wraps NSUserDefaults on iOS/macOS and SharedPreferences on Android.',
    category: 'storage',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/shared_preferences',
    githubUrl: 'https://github.com/flutter/packages/tree/main/packages/shared_preferences',
    docsUrl: 'https://pub.dev/documentation/shared_preferences/latest/',
    installCmd: 'flutter pub add shared_preferences',
    version: '2.3.1',
    likes: 8904,
    pubPoints: 160,
    popularity: 99,
    downloads: '7.8M',
    icon: '💾',
    iconBg: 'linear-gradient(135deg,#34d399,#10b981)',
    tags: ['storage', 'preferences', 'key-value', 'flutter-team'],
    isPremium: false,
    isFeatured: true,
    features: ['Stores strings, bools, ints, doubles & lists', 'Async persistence', 'Platform native caching', 'Mock storage for unit tests', 'Type-safe getters'],
  },
  {
    id: 'flutter_svg',
    name: 'flutter_svg',
    publisher: 'dnfield.dev',
    tagline: 'Render SVG vector files and strings in Flutter widgets',
    description: 'SVG rendering and decoding library for Flutter. Supports rendering vector graphics from assets, network URLs, files, and inline SVG strings with color filters.',
    category: 'ui',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/flutter_svg',
    githubUrl: 'https://github.com/dnfield/flutter_svg',
    docsUrl: 'https://pub.dev/documentation/flutter_svg/latest/',
    installCmd: 'flutter pub add flutter_svg',
    version: '2.0.10+1',
    likes: 7843,
    pubPoints: 160,
    popularity: 98,
    downloads: '6.1M',
    icon: '🎭',
    iconBg: 'linear-gradient(135deg,#ec4899,#be185d)',
    tags: ['svg', 'vector', 'graphics', 'icons'],
    isPremium: false,
    isFeatured: true,
    features: ['Scalable vector rendering', 'SVG asset loading', 'Network SVG with caching', 'Color filtering & blending', 'High-DPI crisp rendering'],
  },
  {
    id: 'google_fonts',
    name: 'google_fonts',
    publisher: 'material.io',
    tagline: 'Use 1,000+ Google Fonts directly in Flutter without bundling files',
    description: 'A Flutter package that allows you to easily use any of the 1,000+ fonts from fonts.google.com in your Flutter app. Automatically downloads and caches fonts on device.',
    category: 'ui',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/google_fonts',
    githubUrl: 'https://github.com/material-foundation/flutter-packages/tree/main/packages/google_fonts',
    docsUrl: 'https://pub.dev/documentation/google_fonts/latest/',
    installCmd: 'flutter pub add google_fonts',
    version: '6.2.1',
    likes: 8012,
    pubPoints: 160,
    popularity: 98,
    downloads: '6.9M',
    icon: '🔤',
    iconBg: 'linear-gradient(135deg,#4285f4,#1a73e8)',
    tags: ['fonts', 'typography', 'google', 'material'],
    isPremium: false,
    isFeatured: true,
    features: ['1,000+ Google Fonts', 'On-demand font loading', 'Offline filesystem caching', 'Dynamic theme integration', 'Supports all weights & styles'],
  },
  {
    id: 'cached_network_image',
    name: 'cached_network_image',
    publisher: 'baseflow.com',
    tagline: 'Flutter library to load, render and cache network images',
    description: 'A Flutter library to show images from the internet and keep them in the cache directory. Provides smooth fade-in animations, loading progress, and error placeholders.',
    category: 'ui',
    platforms: ['android','ios','web','macos','windows'],
    pubDevUrl: 'https://pub.dev/packages/cached_network_image',
    githubUrl: 'https://github.com/Baseflow/flutter_cached_network_image',
    docsUrl: 'https://pub.dev/documentation/cached_network_image/latest/',
    installCmd: 'flutter pub add cached_network_image',
    version: '3.3.1',
    likes: 7354,
    pubPoints: 160,
    popularity: 98,
    downloads: '5.8M',
    icon: '🖼️',
    iconBg: 'linear-gradient(135deg,#7c3aed,#6d28d9)',
    tags: ['image', 'cache', 'network', 'placeholder'],
    isPremium: false,
    isFeatured: true,
    features: ['Disk and memory caching', 'Animated fade transitions', 'Custom progress indicators', 'Error widget fallbacks', 'Image resize on decode'],
  },
  {
    id: 'intl',
    name: 'intl',
    publisher: 'dart.dev',
    tagline: 'Internationalization and localization support for Dart and Flutter',
    description: 'Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting, and bidirectional text.',
    category: 'localization',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/intl',
    githubUrl: 'https://github.com/dart-lang/i18n',
    docsUrl: 'https://pub.dev/documentation/intl/latest/',
    installCmd: 'flutter pub add intl',
    version: '0.19.0',
    likes: 7123,
    pubPoints: 160,
    popularity: 99,
    downloads: '7.5M',
    icon: '🌍',
    iconBg: 'linear-gradient(135deg,#4ade80,#22c55e)',
    tags: ['i18n', 'l10n', 'dates', 'numbers', 'currency'],
    isPremium: false,
    isFeatured: false,
    features: ['Date & time formatting', 'Number & currency formatting', 'Pluralization rules', 'RTL / BiDi text support', 'Multi-language message catalog'],
  },
  {
    id: 'path_provider',
    name: 'path_provider',
    publisher: 'flutter.dev',
    tagline: 'Find commonly used filesystem paths on Android, iOS and Desktop',
    description: 'A Flutter plugin for finding commonly used locations on the filesystem. Supports finding temporary directory, application documents, external storage, and cache folders.',
    category: 'storage',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/path_provider',
    githubUrl: 'https://github.com/flutter/packages/tree/main/packages/path_provider',
    docsUrl: 'https://pub.dev/documentation/path_provider/latest/',
    installCmd: 'flutter pub add path_provider',
    version: '2.1.4',
    likes: 6842,
    pubPoints: 160,
    popularity: 99,
    downloads: '7.1M',
    icon: '📁',
    iconBg: 'linear-gradient(135deg,#10b981,#059669)',
    tags: ['files', 'paths', 'storage', 'directory'],
    isPremium: false,
    isFeatured: false,
    features: ['Get temporary directory', 'Get application documents directory', 'Get application support directory', 'External storage support', 'Cross-platform native'],
  },

  /* ── PRO PACKAGES (Unlocked with FlutterHub Pro Pass) ────────────── */
  {
    id: 'flutter_riverpod',
    name: 'flutter_riverpod',
    publisher: 'dash-overflow.net',
    tagline: 'A reactive caching and state management framework. Provider, perfected.',
    description: 'Riverpod is a complete rewrite of Provider addressing its limitations. It provides compile-time safety, auto-dispose providers, code generation, and powerful DevTools.',
    category: 'state_management',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/flutter_riverpod',
    githubUrl: 'https://github.com/rrousselGit/riverpod',
    docsUrl: 'https://riverpod.dev/',
    installCmd: 'flutter pub add flutter_riverpod',
    version: '2.5.1',
    likes: 9841,
    pubPoints: 160,
    popularity: 97,
    downloads: '3.4M',
    icon: '⚡',
    iconBg: 'linear-gradient(135deg,#7c3aed,#4f46e5)',
    tags: ['state', 'riverpod', 'reactive', 'async'],
    isPremium: true,
    isFeatured: true,
    features: ['Compile-time safety', 'Auto-disposing providers', 'Code generation with riverpod_generator', 'AsyncValue handling', 'Zero BuildContext dependency'],
  },
  {
    id: 'flutter_bloc',
    name: 'flutter_bloc',
    publisher: 'bloclibrary.dev',
    tagline: 'Predictable enterprise state management implementing the BLoC pattern',
    description: 'A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern with strict separation of UI and business logic.',
    category: 'state_management',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/flutter_bloc',
    githubUrl: 'https://github.com/felangel/bloc',
    docsUrl: 'https://bloclibrary.dev/',
    installCmd: 'flutter pub add flutter_bloc',
    version: '8.1.6',
    likes: 10920,
    pubPoints: 160,
    popularity: 98,
    downloads: '4.7M',
    icon: '🧱',
    iconBg: 'linear-gradient(135deg,#4f46e5,#7c3aed)',
    tags: ['state', 'bloc', 'cubit', 'enterprise'],
    isPremium: true,
    isFeatured: true,
    features: ['BlocBuilder & BlocListener', 'Cubit lightweight API', 'BlocObserver logging', 'HydratedBloc persistent state', 'Testable with bloc_test'],
  },
  {
    id: 'dio',
    name: 'dio',
    publisher: 'flutterchina.club',
    tagline: 'Powerful HTTP networking client with interceptors, FormData & cancellation',
    description: 'A powerful HTTP client for Dart and Flutter supporting global configuration, request/response interceptors, FormData uploads, request cancellation, and timeouts.',
    category: 'networking',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/dio',
    githubUrl: 'https://github.com/cfug/dio',
    docsUrl: 'https://pub.dev/documentation/dio/latest/',
    installCmd: 'flutter pub add dio',
    version: '5.4.3+1',
    likes: 9512,
    pubPoints: 160,
    popularity: 97,
    downloads: '4.2M',
    icon: '⚡',
    iconBg: 'linear-gradient(135deg,#06b6d4,#0891b2)',
    tags: ['http', 'dio', 'interceptors', 'uploads'],
    isPremium: true,
    isFeatured: true,
    features: ['Request & response interceptors', 'File upload with progress tracking', 'Cancellation tokens', 'Global transformer & retry policies', 'Cookie management'],
  },
  {
    id: 'firebase_core',
    name: 'firebase_core',
    publisher: 'firebase.google.com',
    tagline: 'Official Flutter plugin to connect to Firebase backend services',
    description: 'Enables connecting to Firebase apps across mobile, desktop, and web. Required as the foundational dependency for all other FlutterFire plugins.',
    category: 'firebase',
    platforms: ['android','ios','web','macos','windows'],
    pubDevUrl: 'https://pub.dev/packages/firebase_core',
    githubUrl: 'https://github.com/firebase/flutterfire',
    docsUrl: 'https://firebase.flutter.dev/',
    installCmd: 'flutter pub add firebase_core',
    version: '3.3.0',
    likes: 6123,
    pubPoints: 140,
    popularity: 96,
    downloads: '5.1M',
    icon: '🔥',
    iconBg: 'linear-gradient(135deg,#f97316,#ea580c)',
    tags: ['firebase', 'google', 'cloud', 'backend'],
    isPremium: true,
    isFeatured: true,
    features: ['Multi-app initialization', 'FlutterFire CLI integration', 'Cross-platform native bridges', 'Cloud configuration sync', 'Web initialization support'],
  },
  {
    id: 'firebase_auth',
    name: 'firebase_auth',
    publisher: 'firebase.google.com',
    tagline: 'Firebase Authentication for Flutter — email, Google, Apple & phone auth',
    description: 'Enables user authentication with email/password, phone SMS OTP, Google, Apple, GitHub, Microsoft, and custom JWT tokens.',
    category: 'authentication',
    platforms: ['android','ios','web','macos'],
    pubDevUrl: 'https://pub.dev/packages/firebase_auth',
    githubUrl: 'https://github.com/firebase/flutterfire',
    docsUrl: 'https://firebase.flutter.dev/docs/auth/overview',
    installCmd: 'flutter pub add firebase_auth',
    version: '5.3.0',
    likes: 6004,
    pubPoints: 140,
    popularity: 96,
    downloads: '4.8M',
    icon: '🔐',
    iconBg: 'linear-gradient(135deg,#f97316,#c2410c)',
    tags: ['auth', 'login', 'firebase', 'security'],
    isPremium: true,
    isFeatured: true,
    features: ['Social sign-in (Google, Apple, etc.)', 'Phone OTP verification', 'Passwordless email link sign-in', 'ID token management', 'State changes stream'],
  },
  {
    id: 'cloud_firestore',
    name: 'cloud_firestore',
    publisher: 'firebase.google.com',
    tagline: 'Cloud Firestore real-time NoSQL cloud database for Flutter',
    description: 'A flexible, scalable NoSQL cloud database for mobile, web, and server development. Provides live document streams and automatic offline persistence.',
    category: 'firebase',
    platforms: ['android','ios','web','macos','windows'],
    pubDevUrl: 'https://pub.dev/packages/cloud_firestore',
    githubUrl: 'https://github.com/firebase/flutterfire',
    docsUrl: 'https://firebase.flutter.dev/docs/firestore/overview',
    installCmd: 'flutter pub add cloud_firestore',
    version: '5.4.0',
    likes: 5832,
    pubPoints: 140,
    popularity: 96,
    downloads: '4.5M',
    icon: '☁️',
    iconBg: 'linear-gradient(135deg,#3b82f6,#1d4ed8)',
    tags: ['firestore', 'nosql', 'database', 'realtime'],
    isPremium: true,
    isFeatured: true,
    features: ['Real-time snapshots stream', 'Offline disk caching', 'Batch writes & transactions', 'Complex collection queries', 'Security rules integration'],
  },
  {
    id: 'lottie',
    name: 'lottie',
    publisher: 'xvrh.dev',
    tagline: 'Render Adobe After Effects JSON animations natively in Flutter',
    description: 'Lottie parses Adobe After Effects animations exported as JSON with Bodymovin and renders them natively on mobile and web with vector fidelity.',
    category: 'animation',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/lottie',
    githubUrl: 'https://github.com/xvrh/lottie-flutter',
    docsUrl: 'https://pub.dev/documentation/lottie/latest/',
    installCmd: 'flutter pub add lottie',
    version: '3.1.2',
    likes: 4521,
    pubPoints: 160,
    popularity: 95,
    downloads: '3.2M',
    icon: '🎞️',
    iconBg: 'linear-gradient(135deg,#06b6d4,#0891b2)',
    tags: ['animation', 'lottie', 'vector', 'motion'],
    isPremium: true,
    isFeatured: true,
    features: ['JSON vector animation playback', 'AnimationController timeline control', 'Asset, file & network sources', 'High performance Skia/Impeller rendering', 'Dynamic color delegates'],
  },
  {
    id: 'flutter_animate',
    name: 'flutter_animate',
    publisher: 'gskinner.com',
    tagline: 'A performant library for chaining declarative animations in Flutter',
    description: 'Add powerful, easy-to-use animations to Flutter widgets using a clean chaining syntax. Supports fade, slide, scale, blur, shimmer, shake, and custom effects.',
    category: 'animation',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/flutter_animate',
    githubUrl: 'https://github.com/gskinner/flutter_animate',
    docsUrl: 'https://pub.dev/documentation/flutter_animate/latest/',
    installCmd: 'flutter pub add flutter_animate',
    version: '4.5.0',
    likes: 3012,
    pubPoints: 160,
    popularity: 92,
    downloads: '1.9M',
    icon: '🎯',
    iconBg: 'linear-gradient(135deg,#c084fc,#a855f7)',
    tags: ['animations', 'chaining', 'effects', 'gskinner'],
    isPremium: true,
    isFeatured: false,
    features: ['Chainable declarative API', 'Fade, scale, slide, blur & shimmer', 'Scroll & gesture driven adapters', 'Sequencing & delay control', 'High performance'],
  },
  {
    id: 'hive_flutter',
    name: 'hive_flutter',
    publisher: 'hivedb.dev',
    tagline: 'Lightweight and blazing fast key-value NoSQL database in pure Dart',
    description: 'Hive is a lightweight and blazing fast key-value database written in pure Dart with zero native dependencies. Supports encryption, box collections, and custom type adapters.',
    category: 'storage',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/hive_flutter',
    githubUrl: 'https://github.com/hivedb/hive',
    docsUrl: 'https://docs.hivedb.dev/',
    installCmd: 'flutter pub add hive_flutter',
    version: '1.1.0',
    likes: 5123,
    pubPoints: 130,
    popularity: 93,
    downloads: '2.8M',
    icon: '🗄️',
    iconBg: 'linear-gradient(135deg,#f59e0b,#d97706)',
    tags: ['database', 'nosql', 'offline', 'fast'],
    isPremium: true,
    isFeatured: false,
    features: ['Zero native dependencies', 'AES-256 box encryption', 'Reactive ValueListenableBuilder', 'Custom object TypeAdapters', 'Microsecond read speeds'],
  },
  {
    id: 'sqflite',
    name: 'sqflite',
    publisher: 'tekartik.com',
    tagline: 'SQLite plugin for Flutter — relational SQL on Android, iOS & macOS',
    description: 'SQLite database plugin for Flutter. Supports transactions, batches, schema migrations, helpers for CRUD queries, and background thread execution.',
    category: 'storage',
    platforms: ['android','ios','macos'],
    pubDevUrl: 'https://pub.dev/packages/sqflite',
    githubUrl: 'https://github.com/tekartik/sqflite',
    docsUrl: 'https://pub.dev/documentation/sqflite/latest/',
    installCmd: 'flutter pub add sqflite',
    version: '2.3.3+1',
    likes: 5621,
    pubPoints: 150,
    popularity: 95,
    downloads: '3.6M',
    icon: '🗃️',
    iconBg: 'linear-gradient(135deg,#3b82f6,#2563eb)',
    tags: ['sql', 'sqlite', 'database', 'relational'],
    isPremium: true,
    isFeatured: false,
    features: ['Full SQLite SQL support', 'Transactions & batch queries', 'Automatic schema versioning', 'Background thread execution', 'Raw SQL and ORM compatibility'],
  },
  {
    id: 'google_maps_flutter',
    name: 'google_maps_flutter',
    publisher: 'flutter.dev',
    tagline: 'Official Google Maps plugin for Flutter',
    description: 'Provides a native Google Maps widget with markers, polylines, polygons, custom map styles, camera positions, and location tracking.',
    category: 'maps',
    platforms: ['android','ios','web'],
    pubDevUrl: 'https://pub.dev/packages/google_maps_flutter',
    githubUrl: 'https://github.com/flutter/packages/tree/main/packages/google_maps_flutter',
    docsUrl: 'https://pub.dev/documentation/google_maps_flutter/latest/',
    installCmd: 'flutter pub add google_maps_flutter',
    version: '2.9.0',
    likes: 5023,
    pubPoints: 140,
    popularity: 95,
    downloads: '3.1M',
    icon: '🗺️',
    iconBg: 'linear-gradient(135deg,#22c55e,#16a34a)',
    tags: ['maps', 'google-maps', 'location', 'gps'],
    isPremium: true,
    isFeatured: false,
    features: ['Interactive vector maps', 'Custom markers & info windows', 'Polylines & polygon geofencing', 'Camera animation controller', 'Custom JSON map styling'],
  },
  {
    id: 'geolocator',
    name: 'geolocator',
    publisher: 'baseflow.com',
    tagline: 'Easy access to platform-specific location services and device GPS',
    description: 'Provides easy access to device GPS, continuous location updates stream, distance calculations, and location permission dialogs.',
    category: 'maps',
    platforms: ['android','ios','web','macos','windows'],
    pubDevUrl: 'https://pub.dev/packages/geolocator',
    githubUrl: 'https://github.com/Baseflow/flutter-geolocator',
    docsUrl: 'https://pub.dev/documentation/geolocator/latest/',
    installCmd: 'flutter pub add geolocator',
    version: '12.0.0',
    likes: 5431,
    pubPoints: 160,
    popularity: 96,
    downloads: '3.8M',
    icon: '📍',
    iconBg: 'linear-gradient(135deg,#ef4444,#dc2626)',
    tags: ['gps', 'location', 'geofence', 'permissions'],
    isPremium: true,
    isFeatured: false,
    features: ['Current GPS coordinates', 'Continuous position stream', 'Distance calculation between points', 'Location permission handler', 'Battery-efficient accuracy settings'],
  },
  {
    id: 'fl_chart',
    name: 'fl_chart',
    publisher: 'iman-neo.dev',
    tagline: 'A powerful and beautiful chart library for Flutter',
    description: 'fl_chart is a highly customizable chart library supporting animated Line Charts, Bar Charts, Pie Charts, Scatter Charts, and Radar Charts with touch interactions.',
    category: 'charts',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/fl_chart',
    githubUrl: 'https://github.com/imaNNeo/fl_chart',
    docsUrl: 'https://pub.dev/documentation/fl_chart/latest/',
    installCmd: 'flutter pub add fl_chart',
    version: '0.68.0',
    likes: 5841,
    pubPoints: 160,
    popularity: 96,
    downloads: '2.9M',
    icon: '📊',
    iconBg: 'linear-gradient(135deg,#fb7185,#e11d48)',
    tags: ['charts', 'graphs', 'line-chart', 'bar-chart'],
    isPremium: true,
    isFeatured: true,
    features: ['Line, Bar, Pie & Radar charts', 'Smooth build and update animations', 'Touch gestures & tooltips', 'Custom gradient fills', 'Highly responsive layout'],
  },
  {
    id: 'image_picker',
    name: 'image_picker',
    publisher: 'flutter.dev',
    tagline: 'Select images and videos from device gallery or camera',
    description: 'A Flutter plugin for picking photos and videos from the user library, and taking new pictures with the camera. Supports multi-image selection and quality compression.',
    category: 'media',
    platforms: ['android','ios','web'],
    pubDevUrl: 'https://pub.dev/packages/image_picker',
    githubUrl: 'https://github.com/flutter/packages/tree/main/packages/image_picker',
    docsUrl: 'https://pub.dev/documentation/image_picker/latest/',
    installCmd: 'flutter pub add image_picker',
    version: '1.1.2',
    likes: 7023,
    pubPoints: 150,
    popularity: 98,
    downloads: '5.4M',
    icon: '📷',
    iconBg: 'linear-gradient(135deg,#c084fc,#a855f7)',
    tags: ['camera', 'gallery', 'photos', 'upload'],
    isPremium: true,
    isFeatured: false,
    features: ['Camera photo & video capture', 'Gallery photo picker', 'Multi-image selection', 'Max width/height resizing', 'JPEG compression quality control'],
  },
  {
    id: 'freezed',
    name: 'freezed',
    publisher: 'dash-overflow.net',
    tagline: 'Code generation for immutable model classes, unions & pattern matching',
    description: 'Freezed is a code generator for immutable classes in Dart. Automatically generates copyWith, toString, operator ==, pattern matching unions, and JSON serialization.',
    category: 'dev_tools',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/freezed',
    githubUrl: 'https://github.com/rrousselGit/freezed',
    docsUrl: 'https://pub.dev/documentation/freezed/latest/',
    installCmd: 'flutter pub add freezed_annotation\nflutter pub add --dev freezed build_runner',
    version: '2.5.7',
    likes: 5841,
    pubPoints: 160,
    popularity: 96,
    downloads: '2.6M',
    icon: '❄️',
    iconBg: 'linear-gradient(135deg,#38bdf8,#0ea5e9)',
    tags: ['codegen', 'immutable', 'unions', 'models'],
    isPremium: true,
    isFeatured: false,
    features: ['Immutable class generation', 'Type-safe copyWith method', 'Union types and pattern matching', 'fromJson / toJson compatibility', 'Deep equality comparison'],
  },
  {
    id: 'go_router',
    name: 'go_router',
    publisher: 'flutter.dev',
    tagline: 'Declarative URL-based routing for Flutter using the Router API',
    description: 'The go_router package provides declarative routing with URL synchronization, deep linking, route redirection guards, nested navigation shells, and type-safe parameters.',
    category: 'dev_tools',
    platforms: ['android','ios','web','macos','windows','linux'],
    pubDevUrl: 'https://pub.dev/packages/go_router',
    githubUrl: 'https://github.com/flutter/packages/tree/main/packages/go_router',
    docsUrl: 'https://pub.dev/documentation/go_router/latest/',
    installCmd: 'flutter pub add go_router',
    version: '14.2.7',
    likes: 5021,
    pubPoints: 160,
    popularity: 96,
    downloads: '3.5M',
    icon: '🗺️',
    iconBg: 'linear-gradient(135deg,#0284c7,#0369a1)',
    tags: ['routing', 'navigation', 'deeplink', 'url'],
    isPremium: true,
    isFeatured: false,
    features: ['Declarative routing table', 'Web browser URL sync', 'Deep link handling', 'ShellRoute bottom bar navigation', 'Authentication redirect guards'],
  },
];

module.exports = {
  PACKAGE_CATEGORIES,
  PACKAGES,
};
